config/routes.rb
Rails.application.routes.draw do
  resources :notadeaulas
  root ‘notadeaula#index’
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notadeaula.rb
class Notadeaula < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notadeaulas_controller.rb
class NotadeaulasController < ApplicationController
  before_action :set_notadeaula, only: [:show, :edit, :update, :destroy]

  # GET /notadeaulas
  # GET /notadeaulas.json
  def index
    @notadeaulas = Notadeaula.all
  end

  # GET /notadeaulas/1
  # GET /notadeaulas/1.json
  def show
  end

  # GET /notadeaulas/new
  def new
    @notadeaula = Notadeaula.new
  end

  # GET /notadeaulas/1/edit
  def edit
  end

  # POST /notadeaulas
  # POST /notadeaulas.json
  def create
    @notadeaula = Notadeaula.new(notadeaula_params)

    respond_to do |format|
      if @notadeaula.save
        format.html { redirect_to @notadeaula, notice: 'Notadeaula was successfully created.' }
        format.json { render :show, status: :created, location: @notadeaula }
      else
        format.html { render :new }
        format.json { render json: @notadeaula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notadeaulas/1
  # PATCH/PUT /notadeaulas/1.json
  def update
    respond_to do |format|
      if @notadeaula.update(notadeaula_params)
        format.html { redirect_to @notadeaula, notice: 'Notadeaula was successfully updated.' }
        format.json { render :show, status: :ok, location: @notadeaula }
      else
        format.html { render :edit }
        format.json { render json: @notadeaula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notadeaulas/1
  # DELETE /notadeaulas/1.json
  def destroy
    @notadeaula.destroy
    respond_to do |format|
      format.html { redirect_to notadeaulas_url, notice: 'Notadeaula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notadeaula
      @notadeaula = Notadeaula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notadeaula_params
      params.require(:notadeaula).permit(:autor, :disciplina, :ano, :semestre, :data, :titulo, :texto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notadeaulas_helper.rb
module NotadeaulasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meuapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notadeaulas/_form.html.erb
<%= form_with(model: notadeaula, local: true) do |form| %>
  <% if notadeaula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notadeaula.errors.count, "error") %> prohibited this notadeaula from being saved:</h2>

      <ul>
      <% notadeaula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor, id: :notadeaula_autor %>
  </div>

  <div class="field">
    <%= form.label :disciplina %>
    <%= form.text_field :disciplina, id: :notadeaula_disciplina %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :notadeaula_ano %>
  </div>

  <div class="field">
    <%= form.label :semestre %>
    <%= form.number_field :semestre, id: :notadeaula_semestre %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data, id: :notadeaula_data %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :notadeaula_titulo %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto, id: :notadeaula_texto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notadeaulas/edit.html.erb
<h1>Editing Notadeaula</h1>

<%= render 'form', notadeaula: @notadeaula %>

<%= link_to 'Show', @notadeaula %> |
<%= link_to 'Back', notadeaulas_path %>

app/views/notadeaulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notadeaulas</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Disciplina</th>
      <th>Ano</th>
      <th>Semestre</th>
      <th>Data</th>
      <th>Titulo</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notadeaulas.each do |notadeaula| %>
      <tr>
        <td><%= notadeaula.autor %></td>
        <td><%= notadeaula.disciplina %></td>
        <td><%= notadeaula.ano %></td>
        <td><%= notadeaula.semestre %></td>
        <td><%= notadeaula.data %></td>
        <td><%= notadeaula.titulo %></td>
        <td><%= notadeaula.texto %></td>
        <td><%= link_to 'Show', notadeaula %></td>
        <td><%= link_to 'Edit', edit_notadeaula_path(notadeaula) %></td>
        <td><%= link_to 'Destroy', notadeaula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notadeaula', new_notadeaula_path %>

app/views/notadeaulas/new.html.erb
<h1>New Notadeaula</h1>

<%= render 'form', notadeaula: @notadeaula %>

<%= link_to 'Back', notadeaulas_path %>

app/views/notadeaulas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @notadeaula.autor %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @notadeaula.disciplina %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @notadeaula.ano %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= @notadeaula.semestre %>
</p>

<p>
  <strong>Data:</strong>
  <%= @notadeaula.data %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @notadeaula.titulo %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @notadeaula.texto %>
</p>

<%= link_to 'Edit', edit_notadeaula_path(@notadeaula) %> |
<%= link_to 'Back', notadeaulas_path %>